# Generated by Django 3.0.5 on 2020-04-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
